In [3]:
import pandas as pd

In [4]:
# load individual datasets
AP = pd.read_csv(r'C:\Users\max\Documents\proj\AP.csv')
breitling = pd.read_csv(r'C:\Users\max\Documents\proj\breitling.csv')
cartier = pd.read_csv(r'C:\Users\max\Documents\proj\cartier.csv')
hublot = pd.read_csv(r'C:\Users\max\Documents\proj\hublot.csv')
IWC = pd.read_csv(r'C:\Users\max\Documents\proj\IWC.csv')
jeager = pd.read_csv(r'C:\Users\max\Documents\proj\jeager.csv')
Longines = pd.read_csv(r'C:\Users\max\Documents\proj\Longines.csv')
omega = pd.read_csv(r'C:\Users\max\Documents\proj\OMEGa.csv')
panerai = pd.read_csv(r'C:\Users\max\Documents\proj\panerai.csv')
patek = pd.read_csv(r'C:\Users\max\Documents\proj\patek.csv')
rolex = pd.read_csv(r'C:\Users\max\Documents\proj\rolex.csv')
seiko = pd.read_csv(r'C:\Users\max\Documents\proj\seiko.csv')
SinnALange = pd.read_csv(r'C:\Users\max\Documents\proj\Sinn-A.Lange.csv')
tagheuer = pd.read_csv(r'C:\Users\max\Documents\proj\tagheuer.csv')
tudor = pd.read_csv(r'C:\Users\max\Documents\proj\tudor.csv')
vacheron = pd.read_csv(r'C:\Users\max\Documents\proj\vacheron.csv')
zenith = pd.read_csv(r'C:\Users\max\Documents\proj\zenith.csv')

In [5]:
# combine 
df = [AP, breitling, cartier, hublot, IWC, jeager, Longines, 
      omega, panerai, patek, rolex, seiko, SinnALange, tagheuer, 
      tudor, vacheron, zenith]

In [6]:
dataframe = pd.concat(df)

In [7]:
dataframe.columns

Index(['web-scraper-order', 'web-scraper-start-url', 'select-brands',
       'select-brands-href', 'aaaaaaaaaaaaaaaaa', 'aaaaaaaaaaaaaaaaa-href',
       'name', 'price', 'brand', 'model', 'ref', 'mvmt', 'casem', 'bracem',
       'yop', 'cond', 'sex', 'size', 'pagination', 'pagination-href',
       'select watch', 'select watch-href', 'title', 'condition', 'movement',
       'gender'],
      dtype='object')

In [17]:
# drop webscrape related columns
dataframe_new = dataframe.drop(['web-scraper-order', 'web-scraper-start-url', 'select-brands',
       'select-brands-href', 'aaaaaaaaaaaaaaaaa', 'aaaaaaaaaaaaaaaaa-href','pagination', 
        'pagination-href','select watch', 'select watch-href', 'gender', 'movement', 'title'], axis=1)

In [18]:
dataframe_new

,name,price,brand,model,ref,mvmt,casem,bracem,yop,cond,sex,size,condition
0,Audemars Piguet Royal Oak Offshore Chronograph...,"$43,500",Audemars Piguet,Royal Oak Offshore Chronograph,26237ST.OO.1000ST.01,NaN,NaN,NaN,2019,Unworn,Men's watch/Unisex,42 mm,NaN
1,Audemars Piguet Royal Oak Selfwinding\n39mm Bl...,"$71,500",Audemars Piguet,Royal Oak Selfwinding,15300ST.OO.1220ST.02,NaN,NaN,NaN,2012,Very good,Men's watch/Unisex,39 mm,NaN
2,Audemars Piguet Royal Oak Chronograph\nBlue Di...,"$79,191",Audemars Piguet,Royal Oak Chronograph,26331ST,Automatic,Steel,Steel,Unknown,Unworn,NaN,41 mm,NaN
3,Audemars Piguet Royal Oak Chronograph\nSelfwin...,"$108,000",Audemars Piguet,Royal Oak Chronograph,26715ST.OO.1356ST.01,Automatic,Steel,Steel,2022 (Approximation),New,Men's watch/Unisex,38 mm,NaN
4,Audemars Piguet Royal Oak Offshore Chronograph...,"$27,500",Audemars Piguet,Royal Oak Offshore Chronograph,26170ST.OO.1000ST.01,Automatic,Steel,Steel,Unknown,Very good,Men's watch/Unisex,42 x 54 mm,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6438,Zenith Defy El Primero\n21 TITANIUM 95.9000.90...,"$9,790",Zenith,Defy El Primero,95.9000.9004/78.M9000,NaN,NaN,NaN,2022,Very good,Men's watch/Unisex,44 mm,NaN
6439,Zenith Chronomaster Sport\n41mm White 03.3100....,"$8,450",Zenith,Chronomaster Sport,03.3100.3600/69.M3100,NaN,NaN,NaN,2021 (Approximation),Very good,Men's watch/Unisex,41 mm,NaN
6440,Zenith El Primero\n50th Anniversary A386 Limited,"$16,500",Zenith,El Primero,30.A386.400/69.C807,NaN,NaN,NaN,2019,Very good,Men's watch/Unisex,38 mm,NaN
6441,Zenith Chronomaster Sport\nWhite Dial Chronogr...,"$9,000",Zenith,Chronomaster Sport,03.3100.3600/69.M3100,NaN,NaN,NaN,2021,Unworn,Men's watch/Unisex,41 mm,NaN
6442,Zenith El Primero Chronomaster\n03.2040.400/69...,"$6,833",Zenith,El Primero Chronomaster,NaN,Automatic,Steel,Leather,2019,Very good,NaN,42 mm,NaN

In [19]:
# clean col names
dataframe_new.rename(columns={"name":"Name", "price":"Price", "brand":"Brand","model":"Model","ref":"Reference Number","mvmt":"Movement","casem":"Case Material","bracem":"Bracelet Material","yop":"Year of Production","cond":"Condition","sex":"Sex","size":"Size","condition":"Condition"})

,Name,Price,Brand,Model,Reference Number,Movement,Case Material,Bracelet Material,Year of Production,Condition,Sex,Size,Condition
0,Audemars Piguet Royal Oak Offshore Chronograph...,"$43,500",Audemars Piguet,Royal Oak Offshore Chronograph,26237ST.OO.1000ST.01,NaN,NaN,NaN,2019,Unworn,Men's watch/Unisex,42 mm,NaN
1,Audemars Piguet Royal Oak Selfwinding\n39mm Bl...,"$71,500",Audemars Piguet,Royal Oak Selfwinding,15300ST.OO.1220ST.02,NaN,NaN,NaN,2012,Very good,Men's watch/Unisex,39 mm,NaN
2,Audemars Piguet Royal Oak Chronograph\nBlue Di...,"$79,191",Audemars Piguet,Royal Oak Chronograph,26331ST,Automatic,Steel,Steel,Unknown,Unworn,NaN,41 mm,NaN
3,Audemars Piguet Royal Oak Chronograph\nSelfwin...,"$108,000",Audemars Piguet,Royal Oak Chronograph,26715ST.OO.1356ST.01,Automatic,Steel,Steel,2022 (Approximation),New,Men's watch/Unisex,38 mm,NaN
4,Audemars Piguet Royal Oak Offshore Chronograph...,"$27,500",Audemars Piguet,Royal Oak Offshore Chronograph,26170ST.OO.1000ST.01,Automatic,Steel,Steel,Unknown,Very good,Men's watch/Unisex,42 x 54 mm,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6438,Zenith Defy El Primero\n21 TITANIUM 95.9000.90...,"$9,790",Zenith,Defy El Primero,95.9000.9004/78.M9000,NaN,NaN,NaN,2022,Very good,Men's watch/Unisex,44 mm,NaN
6439,Zenith Chronomaster Sport\n41mm White 03.3100....,"$8,450",Zenith,Chronomaster Sport,03.3100.3600/69.M3100,NaN,NaN,NaN,2021 (Approximation),Very good,Men's watch/Unisex,41 mm,NaN
6440,Zenith El Primero\n50th Anniversary A386 Limited,"$16,500",Zenith,El Primero,30.A386.400/69.C807,NaN,NaN,NaN,2019,Very good,Men's watch/Unisex,38 mm,NaN
6441,Zenith Chronomaster Sport\nWhite Dial Chronogr...,"$9,000",Zenith,Chronomaster Sport,03.3100.3600/69.M3100,NaN,NaN,NaN,2021,Unworn,Men's watch/Unisex,41 mm,NaN
6442,Zenith El Primero Chronomaster\n03.2040.400/69...,"$6,833",Zenith,El Primero Chronomaster,NaN,Automatic,Steel,Leather,2019,Very good,NaN,42 mm,NaN

In [21]:
# export as csv
dataframe_new.to_csv('Watches.csv', index = True)

In [30]:
# check row num
len(dataframe_new)

284491

In [31]:
# check nulls rows
dataframe_new.isnull().sum()

price      406
brand      131
model    30466
yop        134
cond     75987
sex      95805
size     23597
dtype: int64

In [32]:
# drop null rows
dataframe2 = dataframe_new.dropna(axis=0)

In [33]:
# check length
len(dataframe2)

150611

In [34]:
#look at new df
dataframe2

,price,brand,model,yop,cond,sex,size
0,"$43,500",Audemars Piguet,Royal Oak Offshore Chronograph,2019,Unworn,Men's watch/Unisex,42 mm
1,"$71,500",Audemars Piguet,Royal Oak Selfwinding,2012,Very good,Men's watch/Unisex,39 mm
3,"$108,000",Audemars Piguet,Royal Oak Chronograph,2022 (Approximation),New,Men's watch/Unisex,38 mm
4,"$27,500",Audemars Piguet,Royal Oak Offshore Chronograph,Unknown,Very good,Men's watch/Unisex,42 x 54 mm
5,"$41,000",Audemars Piguet,Royal Oak Offshore Diver,2018 (Approximation),Unworn,Men's watch/Unisex,42 mm
...,...,...,...,...,...,...,...
6436,"$6,671",Zenith,El Primero Chronomaster,Unknown,Good,Men's watch/Unisex,45 mm
6438,"$9,790",Zenith,Defy El Primero,2022,Very good,Men's watch/Unisex,44 mm
6439,"$8,450",Zenith,Chronomaster Sport,2021 (Approximation),Very good,Men's watch/Unisex,41 mm
6440,"$16,500",Zenith,El Primero,2019,Very good,Men's watch/Unisex,38 mm
6441,"$9,000",Zenith,Chronomaster Sport,2021,Unworn,Men's watch/Unisex,41 mm